import React from 'react'

// Each Character component that is generated by the .map() in the App.js
// will pass a prop.isGood that is either true or false
// Using this prop we can dynamically assign the background color of our div
// using inline-styling and a ternary statment
const Character = props => {
    const style = {
        backgroundColor: props.isGood ? "blue" : "red"
    }

    return (
        <div style={style}>
            <h1>{props.name}</h1>
            <p>Weapon: {props.weapon}</p>
            <p>I am a: {props.whatAreYou}</p>
        </div>
    )
}

export default Character